---
title: "About This Website"
---

This website contains course materials for the {{< var course.semester >}} edition of [{{< var course.title >}}]({{< var course.url >}}), taught by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) at [{{< var university.name >}}]({{< var university.url >}}).

## Acknowledgements

Much of the material for this course has evolved from discussions and work with [Klaus Keller](https://engineering.dartmouth.edu/community/faculty/klaus-keller), [Tony Wong](https://tonyewong.github.io/index.html), [Casey Helgeson](https://sites.google.com/site/caseyhelgeson/), [Ben Seiyon Lee](https://sites.google.com/view/benslee/) and [James Doss-Gollin](https://jamesdossgollin.me/). Many thanks also to [Andrew Gelman](https://statmodeling.stat.columbia.edu/) and [Christian Robert](https://xianblog.wordpress.com/), whose work heavily inspired many aspects of this course and which I refer back to regularly. [Kieran Healy](https://kieranhealy.org/) also wrote an [outstanding book on Data Visualization](https://kieranhealy.org/publications/dataviz/) which I learned a great deal from and still reference.

The layout for this site was also inspired by and draws from [STA 210](https://sta210-s22.github.io/website/) at Duke University and [Andrew Heiss's](https://www.andrewheiss.com/teaching/) course materials at Georgia State.

## Tools and Generation Workflow

This website was built with [Quarto](https://quarto.org/), which allows me to integrate [Julia](https://julialang.org/) code and output with the web content, pdfs, and slides in an amazingly clean fashion, while simplifying the process of generation. All materials can be generated through a simple workflow from the [[GitHub Repository]]({{< var course.github >}}).

