---
title: "Exercises"
tbl-colwidths: [20, 5, 10]
---

This page contains information about and a schedule of the homework assignments for the semester.

## General Information

-  While the instructions for each assignment are available through the linked pages for quick and public access, **if you are in the class you must use the link provided in [Ed Discussion](http://us.edstem.org) to accept the assignment**. This will ensure that:
    - You have compatible versions of all relevant packages provided in the environment;
    - You have a GitHub repository that you can use to share your code.
- Submit assignments by 9:00pm Eastern Time on the due date on [Gradescope](https://gradescope.com).
- Submissions must be PDFs. Make sure that you tag the pages corresponding to each question; points will be deducted otherwise.

## Rubric

The standard rubric for homework problems is available [here](rubrics/standard.qmd).

## Schedule

| Week | Instructions | Due Date |
|:----------:|:------------:|:------:|:---------|
| Week 1 | [{{< fa sharp pen-field >}}](exercises/ex01/ex01.qmd) | Feb 02, 2024 |
| Week 3 | [{{< fa sharp pen-field >}}](exercises/ex03/ex03.qmd) | Feb 09, 2024 |
| Week 4 | [{{< fa sharp pen-field >}}](exercises/ex04/ex04.qmd) | Feb 16, 2024 |
| Week 5 | [{{< fa sharp pen-field >}}](exercises/ex05/ex05.qmd) | Feb 23, 2024 |

