---
title: "Homework Assignments"
tbl-colwidths: [20, 5, 10]
engine: julia
---

This page contains information about and a schedule of the homework assignments for the semester.

## General Information

-  While the instructions for each assignment are available through the linked pages for quick and public access, **if you are in the class you must use the link provided in [Ed Discussion](http://us.edstem.org) to accept the assignment**. This will ensure that:
    - You have compatible versions of all relevant packages provided in the environment;
    - You have a GitHub repository that you can use to share your code.
- Submit assignments by 9:00pm Eastern Time on the due date on [Gradescope](https://gradescope.com).
- Submissions must be PDFs. Make sure that you tag the pages corresponding to each question; points will be deducted otherwise.

## Rubric

The standard rubric for homework problems is available [here](rubrics/standard.qmd).

## Schedule

| Assignment | Instructions | Due Date | Solutions |
|:----------:|:------------:|:------:|:---------|
| HW1 | [{{< fa sharp pen-field >}}](hw/hw01/hw01.qmd) | Feb 07, 2025 | [{{< fa sharp key-skeleton >}}]{style="color:grey"}|
| HW2 | [{{< fa sharp pen-field >}}]{style="color:grey"} | Feb 21, 2025 | [{{< fa sharp key-skeleton >}}]{style="color:grey"} |
| HW3 | [{{< fa sharp pen-field >}}]{style="color:grey"} | Mar 07, 2025 | [{{< fa sharp key-skeleton >}}]{style="color:grey"} |
| HW4 | [{{< fa sharp pen-field >}}]{style="color:grey"} | Mar 21, 2025 | [{{< fa sharp key-skeleton >}}]{style="color:grey"} |
| HW5 | [{{< fa sharp pen-field >}}]({style="color:grey"} | Apr 11, 2025 | [{{< fa sharp key-skeleton >}}]{style="color:grey"} |
| HW6 | [{{< fa sharp pen-field >}}]{style="color:grey"} | Apr 25, 2025 | [{{< fa sharp key-skeleton >}}]{style="color:grey"} |
