---
title: Term Project
tbl-colwidths: [20, 5, 10]
---

## Overview

The term project gives you an opportunity to use and extend the methods we have learned in class to an environmental data set and/or model of your choosing. More details will be provided over the semester. We will discuss each component in class as well as providing relevant information on this page.

## Instructions

- Students can work individually or in groups of 2.
- The project proposal should be no more than 2 pages (1-inch margins, 11 point Calibri font or equivalent) and should include a brief summary of the project question and a data and modeling plan. 
- If the project is being done in a group, the proposal should also include a plan for the allocation of duties to each group member (not included in the 2 page limit).
- Presentations should be no more than 10 minutes (this will be timed!) and should capture the key motivation of the project and key methods and results. If we have more projects than can be fit into class on May 5, we will also do presentations on April 30 (we will discuss this by mid-March). 
- Slides for the presentation should be sent to Prof. Srikrishnan by email the evening before the presentation.
- Project reports should be no more than 5 pages (1-inch margins, 11 point Calibri font or equivalent), not including figures and references, but can include an appendix with additional details on methods.

## Schedule

| Milestone |  Due Date |
|:---------:|:-----------|
| Proposal |  Fri, Mar 14 |
| Presentations |  Mon, May 05 |
| Final Report |  Fri, May 16 | 