---
title: "Class Schedule"
tbl-colwidths: [5, 10, 25, 5, 15, 5, 5, 5]
suppress-bibliography: true
---

This page contains a schedule of the topics, content, and assignments for the semester.
Note that this schedule will be updated as necessary the semester progresses, with all changes documented here.

Instructions to save the slides as PDFs can be found [here](https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf). The key is to hit `E` when the slides are open in your browser (ideally Chrome, but it may work in others) to toggle into PDF print mode.

Readings can be accessed using the link (when needed, through the Cornell library with a Cornell login) or on Canvas. 

| Week | Date | Topic | Slides | Reading | Exercises | Homework | 
:-----:|:---------|:---------|:---------:|:------:|:--:|:---:|
| | | ***Hypothesis Testing and Modeling*** | | | |
|  [1](weeks/week01.qmd)   | Mon, Jan 22 | Overview, GitHub Intro | [{{< fa sharp presentation-screen >}}](slides/lecture01-1.qmd){target="_blank"}  | Rockmore ([2024](https://www.newyorker.com/culture/annals-of-inquiry/how-much-of-the-world-is-it-possible-to-model)) | [{{< fa sharp coffee-pot >}}](exercises/ex01/ex01.qmd) | [{{< fa sharp pen-field >}}](assignments/hw01/hw01.qmd) | 
|  | Wed, Jan 24 | Uncertainty and Probability Review | [{{< fa sharp presentation-screen >}}](slides/lecture01-2.qmd) | | | |
| [2](weeks/week02.qmd) | Mon, Jan 29 |  Probability Models and Model Residuals | [{{< fa sharp presentation-screen >}}](slides/lecture02-1.qmd)  | Stein ([2020](https://projecteuclid-org.proxy.library.cornell.edu/journals/statistical-science/volume-35/issue-1/Some-Statistical-Issues-in-Climate-Science/10.1214/19-STS730.full)) | | |
|  | Wed, Jan 31 | Probability Models II  | [{{< fa sharp presentation-screen >}}](slides/lecture02-2.qmd)  | | |  |
| [3](weeks/week03.qmd) | Mon, Feb 5 | Exploratory Data Analysis | [{{< fa sharp presentation-screen >}}](slides/lecture03-1.qmd) | | [{{< fa sharp coffee-pot >}}](exercises/ex03/ex03.qmd) | | 
|  | Wed, Feb 7 | More on Discrepancy and Bayesian Statistics | [{{< fa sharp presentation-screen >}}](slides/lecture03-2.qmd) | | | [{{< fa sharp pen-field >}}](assignments/hw02/hw02.qmd) |
| 4 | Mon, Feb 12 | More Bayes and Extreme Values | [{{< fa sharp presentation-screen >}}](slides/lecture04-1.qmd) | Doss-Gollin et al ([2021](https://iopscience-iop-org.proxy.library.cornell.edu/article/10.1088/1748-9326/ac0278)) | [{{< fa sharp coffee-pot >}}](exercises/ex04/ex04.qmd)  | |
|  | Wed, Feb 14 | *No Class: Project Work* | | | | 
| 5 | Mon, Feb 19 | Extreme Value Theory and Models | [{{< fa sharp presentation-screen >}}](slides/lecture05-1.qmd) | Arns et al ([2013](https://linkinghub-elsevier-com.proxy.library.cornell.edu/retrieve/pii/S0378383913001270)) | [{{< fa sharp coffee-pot >}}](exercises/ex05/ex05.qmd) | | 
|  | Wed, Feb 21 | Data Visualization | [{{< fa sharp presentation-screen >}}](slides/lecture05-2.qmd) | |  |
| 6  | Mon, Feb 26 | *No Class: February Break* | | | | 
|  | Wed, Feb 28 | In-Class Figure Discussion | [{{< fa sharp presentation-screen >}}](slides/lecture06-2.qmd) | | | 
| | | ***Simulation Methods*** | | | |
| 7 | Mon, Mar 4 | Monte Carlo Simulation | [{{< fa sharp presentation-screen >}}](slides/lecture07-1.qmd) | Kale ([2021](https://ieeexplore-ieee-org.proxy.library.cornell.edu/document/9222364/)) | [{{< fa sharp coffee-pot >}}](exercises/ex07/ex07.qmd) |  [{{< fa sharp pen-field >}}](assignments/hw03/hw03.qmd) | 
|  | Wed, Mar 6 | Sampling Distributions and The Bootstrap | [{{< fa sharp presentation-screen >}}](slides/lecture07-2.qmd) | | | 
| 8 | Mon, Mar 11 | The Parametric Bootstrap | [{{< fa sharp presentation-screen >}}](slides/lecture08-1.qmd) | Rahmstorf & Coumou ([2011](http://dx.doi.org/10.1073/pnas.1101766108))  | [{{< fa sharp coffee-pot >}}](exercises/ex08/ex08.qmd) | | 
|  | Wed, Mar 13 | Bayesian Computation | [{{< fa sharp presentation-screen >}}](slides/lecture08-2.qmd) | | | 
| 9 | Mon, Mar 18 | Markov Chain Monte Carlo | [{{< fa sharp presentation-screen >}}](slides/lecture09-1.qmd) | Ruckert et al ([2017](https://link-springer-com.proxy.library.cornell.edu/article/10.1007/s10584-016-1858-z)) | | 
|  | Wed, Mar 20 | MCMC Convergence and Example | [{{< fa sharp presentation-screen >}}](slides/lecture09-2.qmd) | | | 
| 10 | Mon, Mar 25 | MCMC Lab | | | | 
|  | Wed, Mar 27 | Literature Review Presentations | | | |
|   | Mon, Apr 1 | *No Class: Spring Break* | | | |
|   | Wed, Apr 3 | *No Class: Spring Break* | | |  |
| | | ***Model Assessment and Selection*** | | | |
| 11 | Mon, Apr 8 | *No Class: Eclipse* | | |  |
|  | Wed, Apr 10 | Hypothesis Testing | [{{< fa sharp presentation-screen >}}](slides/lecture11-2.qmd) | | |
| 12 | Mon, Apr 15 | Model Assessment | [{{< fa sharp presentation-screen >}}](slides/lecture12-1.qmd) | | | [{{< fa sharp pen-field >}}](assignments/hw04/hw04.qmd) | 
| 13 | Wed, Apr 17 | Cross-Validation and Information Criteria | [{{< fa sharp presentation-screen >}}](slides/lecture12-2.qmd) | | | 
| 1 | Mon, Apr 22 | Model Assessment and Selection: Examples | | |  |
|  | Wed, Apr 24 |  Missing Data Models | | | | 
| | | ***Emulation*** | | | |
| 14 | Mon, Apr 29 | Tradeoffs Between Complexity and Ensemble Size | | | | 
|  | Wed, May 1 | Emulating Expensive Models | | | | 
| 15 | Mon, May 6 | Project Presentations | | | | 
