---
title: "Week 5 Information"
---

## Lectures

- [Bayesian Statistics](../slides/lecture05-1-bayes.qmd)

## Homework

- [Homework 2](../hw/hw02/hw02.qmd) due 2/21/25 by 9PM.

## Readings

- Gelman, A., & Shalizi, C. R. (2013). Philosophy and the practice of Bayesian statistics. The British Journal of Mathematical and Statistical Psychology, 66(1), 8–38. <https://doi.org/10.1111/j.2044-8317.2011.02037.x>

  As you're reading, please use the collaborative annotation in Canvas to make notes and read and respond to others' thoughts and questions. We will discuss the paper in the 02/24 class period. You will be graded based on annotation and participation in the discussion.

  In particular, please focus on:

  * What are the practical differences between the varying philosophical perspectives provided in the paper?
  * What do you think about the authors' recommendations about iterative model checking and building?
  
  This paper draws more on applied social science than environmental science, but feel free to think about environmental analogues to any examples or considerations.


## Quiz

- Quiz due Monday.