---
title: "Week 3 Information"
---

## Lectures

- [Probability Models for Data](../slides/lecture03-1-probmodels.qmd)
- [Time Series](../slides/lecture03-2-timeseries.qmd)

## Homework

- [Homework 1](../hw/hw01/hw01.qmd) due 2/7/25 by 9PM.

## Readings

- Shmueli, G. (2010). To explain or to predict? *Statistical Science: A Review Journal of the Institute of Mathematical Statistics*, 25(3), 289–310. <https://doi.org/10.1214/10-STS330>


  As you're reading, please use the collaborative annotation in Canvas to make notes and read and respond to others' thoughts and questions. We will discuss the paper in the 02/10 class period. You will be graded based on annotation and participation in the discussion.

  In particular, please focus on:

  * What differentiates the explanation vs. predictive modeling paradigms? How does this relate to the choices we've discussed that are involved in statistical modeling?
  * What are the dangers in conflating explanation and prediction?
  * Is it possible to fully separate explanation and prediction? Why or why not?
  
  This paper is quite broad, and includes discussion of topics that we will not cover until later in the semester (such as model validation and selection). It's ok to gloss over these, particularly if the terminology is unknown to you, but keep them in mind as we move forward!
