---
title: "Project Proposal Instructions"
---

Your project should involve analyzing a data set of interest using model-based simulation. The proposal is an opportunity to think through and articulate the core science question, hypotheses, and modeling approaches, and get feedback about the plan.

## What Makes A Good Project?

Your project topic should have the following features:

* Focus on a data set which can inform a relevant science question;
* Involve one or more specific hypotheses which can be translated into a simulation model (either numerical or statistical is fine);
* If only one hypothesis is considered, a meaningful "null" model should be included for comparison.

## Proposal Guidelines

The proposal should have the following components, and be no more than 5 pages (not including references and plots) with 1 inch margins (on all sides) and at least 11 point font.

* **Background**: What is the scientific context of your project? What question are you trying to address and why does it matter? What are the hypotheses you are focusing on?
* **Data Overview**: Where was the data obtained from? In what context was it collected (*e.g.* is it observational data, collected in a lab, or reconstructed) and what implications that might have for its use in testing your hypotheses? Include some exploratory analysis and plots. Are there errors included in the data? Will you need any auxiliary data?
* **Model Specification**: What model(s) are you proposing to use to study the data in the context of your hypotheses? If you're using a numerical simulation model, what parameters will you treat as uncertain and what is the probability model for the residuals? If you're using a statistical model, what choices are you making about distributions? Include some initial exploratory analyses to analyze initial goodness-of-fit.
* **References**: Make sure to include any references cited in your proposal.